import numpy as np
import matplotlib.pylab as plt
Data= np.genfromtxt('tray.txt')
plt.plot(Data[:,0],Data[:,1])
plt.xlabel("t (segundos)")
plt.ylabel("x (metros)")
plt.title('posición particula')
plt.legend()
plt.grid()
plt.savefig('pos.png')
plt.figure()
plt.plot(Data[:,0],Data[:,2])
plt.xlabel("t (segundos)")
plt.ylabel("v (m/s)")
plt.title('velocidad particula')
plt.legend()
plt.grid()
plt.savefig('vel.png')
plt.figure()
plt.plot(Data[:,1],Data[:,2])
plt.xlabel("x (metros)")
plt.ylabel("v (m/s)")
plt.title('fase particula')
plt.legend()
plt.grid()
plt.savefig('phase.png')
